main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.Home.as_view(), name='home'),
    path('food/', views.foods_index, name='foods_index'),
    path('foodlog/', views.food_log, name='food_log'),
    path('food/create/', views.FoodCreate.as_view(), name='foods_create'),
    path('food/<int:pk>/delete/', views.FoodDelete.as_view(), name='foods_delete'),
    path('exercise/', views.exercises_index, name='exercises_index'),
    path('exerciselog/', views.exercise_log, name='exercise_log'),
    path('exercise/create/', views.ExerciseCreate.as_view(), name='exercises_create'),
    path('exercise/<int:pk>/delete', views.ExerciseDelete.as_view(), name='exercises_delete'),
    path('accounts/signup/', views.signup, name='signup'),
    path('accounts/createprofile/', views.createprofile, name='createprofile'),
    path('profile/', views.profile, name='profile'),
    path('profile/update/', views.updateprofile, name='updateprofile'),
    path('meal/create', views.MealCreate.as_view(), name='meal_create'),
    path('meal/<int:meal_id>/', views.meal_details, name='meal_details'),
    path('meal/<int:meal_id>/assoc_food/<int:food_id>', views.assoc_food, name='assoc_food'),
    path('meal/<int:meal_id>/disassoc_food/<int:food_id>', views.disassoc_food, name='disassoc_food')
]

thehustle/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls'))
]

main_app/models.py
from os import name
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from datetime import date


TYPES = (
    ('B', 'Breakfast'),
    ('L', 'Lunch'),
    ('D', 'Dinner')
)

# Create your models here.
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    age = models.IntegerField()
    height = models.IntegerField('Height in inches')
    weight = models.IntegerField('Weight in lbs')
    goal_weight = models.IntegerField('Goal weight in lbs')


class Food(models.Model):
    name = models.CharField(max_length=100)
    protein = models.IntegerField('Protein in grams')
    carbs = models.IntegerField('Carbs in grams')
    fat = models.IntegerField('Fat in grams')
    sugar = models.IntegerField('Sugar in grams')
    calories = models.IntegerField()
    sodium = models.IntegerField('Sodium in milligrams')
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class Meal(models.Model):
    name = models.CharField(
        max_length=1,
        choices=TYPES,
        default=TYPES[0][0]
    )
    date = models.DateField()
    foods = models.ManyToManyField(Food)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('meal_details', kwargs={'meal_id': self.id})

    # def lunch_count(self):
    #     return self.lunch_set.filter(name=TYPES[1][0]).count()

    @property
    def get_total_calories(self):
        return sum([food.calories for food in self.foods.all()])

    @property
    def get_total_protein(self):
        return sum([food.protein for food in self.foods.all()])

    @property
    def get_total_carbs(self):
        return sum([food.carbs for food in self.foods.all()])

    @property
    def get_total_fat(self):
        return sum([food.fat for food in self.foods.all()])

    @property
    def get_total_sugar(self):
        return sum([food.sugar for food in self.foods.all()])

    @property
    def get_total_sodium(self):
        return sum([food.sodium for food in self.foods.all()])
    



class Exercise(models.Model):
    name = models.CharField(max_length=50)
    description = models.CharField(max_length=250)
    duration = models.IntegerField('Duration in minutes')
    calories_burned = models.IntegerField()
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

main_app/forms.py
# from django.db.models import fields
from django.forms import ModelForm
from .models import Profile

class ProfileForm(ModelForm):
    class Meta:
        model = Profile
        fields = ['age', 'height', 'weight', 'goal_weight']

class UpdateProfileForm(ModelForm):
    class Meta:
        model = Profile
        fields = ['user', 'weight', 'goal_weight']
        

main_app/views.py
from os import error
from django.contrib.auth.models import User
from django.db.models import query
from django.db.models.aggregates import Sum
from django.shortcuts import redirect, render
from django.views.generic.edit import CreateView, DeleteView
from django.contrib.auth.views import LoginView
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from .forms import ProfileForm, UpdateProfileForm
from .models import Exercise, Food, Meal, Profile




# Create your views here.
class Home(LoginView):
    template_name = 'home.html'


@login_required
def profile(request):
    profile = Profile.objects.filter(user=request.user)
    return render(request, 'profile.html', { 'profile': profile })


@login_required
def foods_index(request):
    foods = Food.objects.filter(user=request.user)
    return render(request, 'foods/index.html', { 'foods': foods })


@login_required
def food_log(request):
    foods = Food.objects.filter(user=request.user)
    meals = Meal.objects.filter(user=request.user)
    profile = Profile.objects.filter(user=request.user)
    # total_calories = Sum([foods.calories for foods in meals.food.all])
    return render(request, 'foods/log.html', { 'foods': foods, 'meals': meals, 'profile': profile })


@login_required
def exercises_index(request):
    exercises = Exercise.objects.filter(user=request.user)
    return render(request, 'exercises/index.html', { 'exercises': exercises })


@login_required
def exercise_log(request):
    exercises = Exercise.objects.filter(user=request.user)
    return render(request, 'exercises/log.html', { 'exercises': exercises })


@login_required
def meal_details(request, meal_id):
    meal = Meal.objects.get(id=meal_id)
    profile = Profile.objects.filter(user=request.user)
    unadded_foods = Food.objects.exclude(id__in = meal.foods.all().values_list('id'))
    return render(request, 'meals/meal_details.html', {'meal': meal, 'foods': unadded_foods, 'profile': profile })


class MealCreate(LoginRequiredMixin, CreateView):
    model = Meal
    fields = ['name', 'date']

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class FoodCreate(LoginRequiredMixin, CreateView):
    model = Food
    fields = ['name', 'calories', 'protein', 'carbs', 'fat', 'sugar', 'sodium']
    success_url = '/food/'

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class FoodDelete(LoginRequiredMixin, DeleteView):
    model = Food
    success_url = '/food/'


class ExerciseCreate(LoginRequiredMixin, CreateView):
    model = Exercise
    fields = ['name', 'description', 'duration', 'calories_burned']
    success_url = '/exercise/'

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class ExerciseDelete(LoginRequiredMixin, DeleteView):
    model = Exercise
    success_url = '/exercise/'


@login_required
def assoc_food(request,  meal_id, food_id):
    Meal.objects.get(id=meal_id).foods.add(food_id)
    return redirect('meal_details', meal_id=meal_id)


@login_required
def disassoc_food(request, meal_id, food_id):
    Meal.objects.get(id=meal_id).foods.remove(food_id)
    return redirect('meal_details', meal_id=meal_id)


def signup(request):
    error_message = ''
    if request.method == 'POST':
        user_form = UserCreationForm(request.POST)
        if user_form.is_valid():
            user = user_form.save()
            login(request, user)
            return redirect('createprofile')
        else:
            error_message = 'Invalid sign up - try again'

    user_form = UserCreationForm()
    context = {'user_form': user_form, 'error_message': error_message}
    return render(request, 'signup.html', context)


def createprofile(request):
    error_message = ''
    if request.method == 'POST':
        profile_form = ProfileForm(request.POST)
        if profile_form.is_valid():
            user_profile = profile_form.save(commit = False)
            user_profile.user_id = request.user.id
            user_profile.save()
            return redirect('foods_index')
        else:
            error_message = 'Invalid - try again'

    profile_form = ProfileForm()
    context = {'profile_form': profile_form, 'error_message': error_message}
    return render(request, 'createprofile.html', context)


def updateprofile(request):
    error_message = ''
    if request.method == 'POST':
        update_profile_form = UpdateProfileForm(request.POST)
        if update_profile_form.is_valid():
            update_profile_form.save()
            return redirect('profile')
        else:
            error_message = 'Invalid - try again'

    update_profile_form = UpdateProfileForm()
    context = {'update_profile_form': update_profile_form, 'error_message': error_message}
    return render(request, 'updateprofile.html', context)

main_app/templates/foods/index.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<link rel="stylesheet" type='text/css' href="{% static 'css/food-index.css' %}">
{% endblock %}

{% block content %}

<section class='food-form'>
    <div class='form-container'>
        <h1>Add a Food</h1>
    </div>
    <div class='add-food-btn'>
        <a href="{% url 'foods_create' %}" class='add-food-btn'>Click to add a food</a>
    </div>
</section>


<section class='all-foods'>
    <div class='food-container'>
        <h1 class='title'>Your Foods</h1>
        <div class='foods-list'>
            {% for food in foods %}
                <div class='test'>
                    <h3>{{ food.name }}</h3>
                    <table class='food-table'>
                        <thead>
                            <tr>
                                <th>Calories</th>
                                <th>Protein</th>
                                <th>Carbs</th>
                                <th>Fat</th>
                                <th>Sugar</th>
                                <th>Sodium</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td>{{ food.calories }}</td>
                                <td>{{ food.protein }}g</td>
                                <td>{{ food.carbs }}g</td>
                                <td>{{ food.fat }}g</td>
                                <td>{{ food.sugar }}g</td>
                                <td>{{ food.sodium }}mg</td>
                            </tr>
                        </tbody>
                    </table>
                    <a href="{% url 'foods_delete' food.id %}" class='delete-btn'>Delete</a>
                    <hr>
                </div>
            {% endfor %}
        </div>
    </div>
</section>

{% endblock %}

main_app/templates/foods/log.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<link rel="stylesheet" href="{% static 'css/food-log.css' %}">
{% endblock %}

{% block content %}
<h1 class='title'>Your Meals</h1>
<div class="container">
    <div class='breakfast'>
        <h1>Breakfast</h1>
        <h3>Add a new breakfast meal</h3>
        <a href="{% url 'meal_create' %}" class='add-meal-btn'>Add</a>
        <div class='meal-list'>
            {% for meal in meals %}
                {% if meal.name == 'B' %}
                    <h1>{{ meal.get_name_display }} on {{ meal.date }}</h1>
                    <a href="{% url 'meal_details' meal.id %}" class='meal-deets'>View</a>
                    <hr>
                {% endif %}
            {% endfor %}
        </div>
    </div>
    <div class='lunch'>
        <h1>Lunch</h1>
        <h3>Add a new lunch meal</h3>
        <a href="{% url 'meal_create' %}" class='add-meal-btn'>Add</a>
        <div class='meal-list'>
            {% for meal in meals %}
                {% if meal.name == 'L' %}
                    <h1>{{ meal.get_name_display }} on {{ meal.date }}</h1>
                    <a href="{% url 'meal_details' meal.id %}" class='meal-deets'>View</a>
                    <hr>
                {% endif %}
            {% endfor %}
        </div>           
    </div>
    <div class='dinner'>
        <h1>Dinner</h1>
        <h3>Add a new dinner meal</h3>
        <a href="{% url 'meal_create' %}" class='add-meal-btn'>Add</a>
        <div class='meal-list'>
            {% for meal in meals %}
                {% if meal.name == 'D' %}
                    <h1>{{ meal.get_name_display }} on {{ meal.date }}</h1>
                    <a href="{% url 'meal_details' meal.id %}" class='meal-deets'>View</a>
                    <hr>
                {% endif %}
            {% endfor %}
        </div>
    </div>
</div>

{% endblock %}